"""add_task_assigner_chat_table

Revision ID: 14ea992d4e0c
Revises: 37644ee864a1
Create Date: 2026-03-18 02:22:49.746971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ea992d4e0c'
down_revision: Union[str, Sequence[str], None] = '37644ee864a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_assigner_chats_project_id'), 'task_assigner_chats', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_assigner_chats_project_id'), table_name='task_assigner_chats')
    # ### end Alembic commands ###
