"""create users table  and channel_mapping table

Revision ID: 404a4c7debcd
Revises: dcffa6d79d63
Create Date: 2026-03-10 10:32:25.522759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404a4c7debcd'
down_revision: Union[str, Sequence[str], None] = 'dcffa6d79d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
