"""create workspace table

Revision ID: a1aeb48c3683
Revises: 
Create Date: 2026-03-09 23:31:55.661889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1aeb48c3683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('workspace_name', sa.String(), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspaces')
    # ### end Alembic commands ###
