"""Add slack_channel_id to projects

Revision ID: c353b40bba45
Revises: fd320b326da5
Create Date: 2026-03-18 13:50:48.464501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c353b40bba45'
down_revision: Union[str, Sequence[str], None] = 'fd320b326da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slack_channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'slack_channel_id')
    # ### end Alembic commands ###
