import enum

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from src.backend.model.base import BaseModel


# ── Enums ──────────────────────────────────────────────────────────────────────


class MeetingType(str, enum.Enum):
    SCHEDULED = "scheduled"
    ESCALATION = "escalation"
    STANDUP = "standup"
    AD_HOC = "ad_hoc"


class MeetingStatus(str, enum.Enum):
    SCHEDULED = "scheduled"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class InviteSource(str, enum.Enum):
    AI_SUGGESTED = "ai_suggested"
    MANUALLY_ADDED = "manually_added"


class ParticipantRole(str, enum.Enum):
    HOST = "host"
    PRESENTER = "presenter"
    ATTENDEE = "attendee"


class TranscriptStatus(str, enum.Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class ActionItemStatus(str, enum.Enum):
    PENDING = "pending"
    CONVERTED_TO_TASK = "converted_to_task"
    DISMISSED = "dismissed"


# ── Models ─────────────────────────────────────────────────────────────────────


class Meeting(BaseModel):
    """
    Core record for a single meeting session.

    ``bot_session_id`` is the short UUID generated by MultiSessionOrchestrator
    and written here as soon as the bot starts so the runtime session and the
    DB record can always be correlated.

    ``task_id`` is nullable — it is populated when the meeting was auto-triggered
    by an unresolved task conflict from Module 2 (escalation flow).
    """

    __tablename__ = "meetings"

    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False)
    created_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)

    # Optional link to the task that triggered this meeting (escalation flow).
    task_id = Column(UUID(as_uuid=True), ForeignKey("tasks.id"), nullable=True)

    title = Column(String, nullable=False)
    meet_url = Column(String, nullable=False)

    # The short session ID produced by MultiSessionOrchestrator (e.g. "a3f8c12b").
    # Written immediately when the bot starts so logs & DB can be correlated.
    bot_session_id = Column(String, nullable=True, index=True)

    meeting_type = Column(
        Enum(MeetingType, name="meeting_type_enum"),
        nullable=False,
        default=MeetingType.SCHEDULED,
    )
    status = Column(
        Enum(MeetingStatus, name="meeting_status_enum"),
        nullable=False,
        default=MeetingStatus.SCHEDULED,
    )

    agenda = Column(Text, nullable=True)

    # Planned time vs. actual start/end filled by the bot.
    scheduled_at = Column(DateTime(timezone=True), nullable=True)
    started_at = Column(DateTime(timezone=True), nullable=True)
    ended_at = Column(DateTime(timezone=True), nullable=True)

    # ── Relationships ──────────────────────────────────────────────────────────
    participants = relationship(
        "MeetingParticipant", back_populates="meeting", cascade="all, delete-orphan"
    )
    transcript = relationship(
        "MeetingTranscript",
        back_populates="meeting",
        uselist=False,
        cascade="all, delete-orphan",
    )
    summary = relationship(
        "MeetingSummary",
        back_populates="meeting",
        uselist=False,
        cascade="all, delete-orphan",
    )
    action_items = relationship(
        "MeetingActionItem", back_populates="meeting", cascade="all, delete-orphan"
    )


class MeetingParticipant(BaseModel):
    """
    Tracks every person invited to (and/or who attended) a meeting.

    ``joined_at`` / ``left_at`` are filled in real-time by the bot as it
    detects participant changes; they replace the coarse ``attended: bool``
    anti-pattern.
    """

    __tablename__ = "meeting_participants"

    meeting_id = Column(UUID(as_uuid=True), ForeignKey("meetings.id"), nullable=False)
    project_member_id = Column(
        UUID(as_uuid=True), ForeignKey("project_members.id"), nullable=False
    )

    invite_source = Column(
        Enum(InviteSource, name="invite_source_enum"),
        nullable=False,
        default=InviteSource.MANUALLY_ADDED,
    )
    # AI-generated rationale, e.g. "Owns Task X; blocked by dependency Y."
    invite_reason = Column(Text, nullable=True)

    role_in_meeting = Column(
        Enum(ParticipantRole, name="participant_role_enum"),
        nullable=False,
        default=ParticipantRole.ATTENDEE,
    )

    # Actual attendance window — filled by the bot during the session.
    joined_at = Column(DateTime(timezone=True), nullable=True)
    left_at = Column(DateTime(timezone=True), nullable=True)

    # ── Relationships ──────────────────────────────────────────────────────────
    meeting = relationship("Meeting", back_populates="participants")

    __table_args__ = (
        UniqueConstraint(
            "meeting_id", "project_member_id", name="uq_meeting_participant"
        ),
    )


class MeetingTranscript(BaseModel):
    """
    Stores the audio-to-text transcript for a completed meeting.

    ``segments`` is a JSONB array of speaker-attributed chunks:
        [
          {
            "sequence": 0,
            "start_ms": 0,
            "end_ms": 4200,
            "speaker_label": "Speaker 1",
            "speaker_member_id": "<uuid or null>",
            "text": "Let's get started."
          },
          ...
        ]

    ``raw_text`` is the full concatenated transcript for full-text search and
    passing as a single context window to the summarization AI.
    """

    __tablename__ = "meeting_transcripts"

    meeting_id = Column(
        UUID(as_uuid=True), ForeignKey("meetings.id"), nullable=False, unique=True
    )

    status = Column(
        Enum(TranscriptStatus, name="transcript_status_enum"),
        nullable=False,
        default=TranscriptStatus.PENDING,
    )
    language = Column(String(8), nullable=True, default="en")
    provider = Column(String, nullable=True)  # e.g. "whisper", "google_stt"
    raw_text = Column(Text, nullable=True)
    segments = Column(JSONB, nullable=True)
    word_count = Column(Integer, nullable=True)

    # ── Relationships ──────────────────────────────────────────────────────────
    meeting = relationship("Meeting", back_populates="transcript")


class MeetingSummary(BaseModel):
    """
    AI-generated post-meeting summary and extracted structured intelligence.

    ``key_decisions`` is a JSONB array:
        [{"description": "...", "decided_by_name": "...", "timestamp_ms": 0}]

    ``risks_and_blockers`` is a JSONB array that feeds Module 3:
        [{"description": "...", "severity": "high", "related_task_id": "<uuid or null>"}]
    """

    __tablename__ = "meeting_summaries"

    meeting_id = Column(
        UUID(as_uuid=True), ForeignKey("meetings.id"), nullable=False, unique=True
    )

    summary_text = Column(Text, nullable=True)
    key_decisions = Column(JSONB, nullable=True)
    risks_and_blockers = Column(JSONB, nullable=True)

    ai_model = Column(String, nullable=True)  # e.g. "gemini-1.5-pro"
    generated_at = Column(DateTime(timezone=True), nullable=True)

    # If the summary was published to a project document (Module 1).
    document_id = Column(UUID(as_uuid=True), ForeignKey("documents.id"), nullable=True)

    # ── Relationships ──────────────────────────────────────────────────────────
    meeting = relationship("Meeting", back_populates="summary")


class MeetingActionItem(BaseModel):
    """
    An individual action item extracted from the meeting by AI.

    Lifecycle: PENDING → CONVERTED_TO_TASK (when Module 2 creates a Task from
    this row) or DISMISSED (manually rejected).

    Task promotion direction: the ``tasks`` table (Module 2) is expected to
    carry a nullable ``source_action_item_id`` FK pointing back here — this
    table intentionally does NOT reference tasks to keep Module 4 self-contained.
    """

    __tablename__ = "meeting_action_items"

    meeting_id = Column(UUID(as_uuid=True), ForeignKey("meetings.id"), nullable=False)

    description = Column(Text, nullable=False)

    # Verbatim quote from the transcript that triggered this extraction.
    source_quote = Column(Text, nullable=True)

    assigned_to_member_id = Column(
        UUID(as_uuid=True), ForeignKey("project_members.id"), nullable=True
    )
    due_date = Column(DateTime(timezone=True), nullable=True)

    status = Column(
        Enum(ActionItemStatus, name="action_item_status_enum"),
        nullable=False,
        default=ActionItemStatus.PENDING,
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    meeting = relationship("Meeting", back_populates="action_items")
