"""resolve_schema_mismatch

Revision ID: 0aede12fdc05
Revises: 3c3f0d1b07d6
Create Date: 2026-03-19 02:08:41.765700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aede12fdc05'
down_revision: Union[str, Sequence[str], None] = '3c3f0d1b07d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --- FIX ENUM CASE MISMATCH (rename UPPERCASE to lowercase) ---
    # task_status_enum
    op.execute("ALTER TYPE task_status_enum RENAME VALUE 'TODO' TO 'todo'")
    op.execute("ALTER TYPE task_status_enum RENAME VALUE 'IN_PROGRESS' TO 'in_progress'")
    op.execute("ALTER TYPE task_status_enum RENAME VALUE 'COMPLETED' TO 'completed'")
    op.execute("ALTER TYPE task_status_enum RENAME VALUE 'BLOCKED' TO 'blocked'")

    # task_priority_enum
    op.execute("ALTER TYPE task_priority_enum RENAME VALUE 'HIGH' TO 'high'")
    op.execute("ALTER TYPE task_priority_enum RENAME VALUE 'MEDIUM' TO 'medium'")
    op.execute("ALTER TYPE task_priority_enum RENAME VALUE 'LOW' TO 'low'")

    # task_complexity_enum
    op.execute("ALTER TYPE task_complexity_enum RENAME VALUE 'LOW' TO 'low'")
    op.execute("ALTER TYPE task_complexity_enum RENAME VALUE 'MEDIUM' TO 'medium'")
    op.execute("ALTER TYPE task_complexity_enum RENAME VALUE 'HIGH' TO 'high'")

    # task_category_enum
    op.execute("ALTER TYPE task_category_enum RENAME VALUE 'BACKEND' TO 'backend'")
    op.execute("ALTER TYPE task_category_enum RENAME VALUE 'FRONTEND' TO 'frontend'")
    op.execute("ALTER TYPE task_category_enum RENAME VALUE 'DATABASE' TO 'database'")
    op.execute("ALTER TYPE task_category_enum RENAME VALUE 'AI_ML' TO 'ai_ml'")
    op.execute("ALTER TYPE task_category_enum RENAME VALUE 'DEVOPS' TO 'devops'")
    op.execute("ALTER TYPE task_category_enum RENAME VALUE 'QA' TO 'qa'")
    op.execute("ALTER TYPE task_category_enum RENAME VALUE 'SECURITY' TO 'security'")

    # background_enum
    op.execute("ALTER TYPE background_enum RENAME VALUE 'TECHNICAL' TO 'technical'")
    op.execute("ALTER TYPE background_enum RENAME VALUE 'NON_TECHNICAL' TO 'non_technical'")

    op.add_column('project_members', sa.Column('background', sa.Enum('technical', 'non_technical', name='background_enum'), nullable=True))
    op.add_column('projects', sa.Column('slack_channel_id', sa.String(), nullable=True))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('active', 'completed', 'hold', name='projectstatus'),
               nullable=False,
               postgresql_using="status::projectstatus")
    op.drop_index(op.f('idx_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_project_member_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_member_id'), 'tasks', ['project_member_id'], unique=False)
    op.add_column('user_details', sa.Column('experience_years', sa.String(), nullable=True))
    op.drop_column('user_details', 'experience')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('invited', 'active', 'deactivated', name='userstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'is_verified')
    op.add_column('user_details', sa.Column('experience', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_details', 'experience_years')
    op.drop_index(op.f('ix_tasks_project_member_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    # op.create_index(op.f('idx_tasks_project_member_id'), 'tasks', ['project_member_id'], unique=False)
    # op.create_index(op.f('idx_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('active', 'completed', 'hold', name='projectstatus'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('projects', 'slack_channel_id')
    op.drop_column('project_members', 'background')

    # Downgrade renames (back to UPPERCASE)
    op.execute("ALTER TYPE task_status_enum RENAME VALUE 'todo' TO 'TODO'")
    op.execute("ALTER TYPE task_status_enum RENAME VALUE 'in_progress' TO 'IN_PROGRESS'")
    op.execute("ALTER TYPE task_status_enum RENAME VALUE 'completed' TO 'COMPLETED'")
    op.execute("ALTER TYPE task_status_enum RENAME VALUE 'blocked' TO 'BLOCKED'")
    # ... and so on for others if needed ...
    # ### end Alembic commands ###
